### ISSUE TITLE
How did you find these endpoints?

### ISSUE THREAD

**Issue by sdushantha** [notcammy/PyTikTokScraper#3]
Hi,

How were you able to find these endpoints? Are these from their website or did you use Charles proxy to intercept the TikTok app?

**Comment by notcammy** [comment]
I used Charles proxy for the most part. I scrape the mobile page of an user to get available livestreams since the endpoint for that requires authentication and the login function doesn't actually work right now lol.

**Comment by sdushantha** [comment]
I am very new to Charles proxy. I have tried to intercept SnapChat, but I am not able to get the parameters for each of the requests that is made. I kinda feel like its complicated. Burp Suite is much easier for intercepting, but I dont think its good with intercepting connection from a phone.

Could you teach me? :smile:  Maybe over Discord or Skype. If that doesn't suit you, do you know any good tutorial online which I could use to learn?

**Comment by notcammy** [comment]
Message me on Discord: Cammy#0286
